
-- Incorporado el 10-11-2018 por autor Omega
-- 
DROP DATABASE IF EXISTS `PADELDB`;
CREATE DATABASE `PADELDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
--
-- SELECCIONAMOS PARA USAR
--
USE `PADELDB`;
--
-- DAMOS PERMISO USO Y BORRAMOS EL USUARIO QUE QUEREMOS CREAR POR SI EXISTE
--
GRANT USAGE ON *.* TO `PADELDB`@`localhost`;
  DROP USER `PADELDB`@`localhost`;
--
-- CREAMOS EL USUARIO Y LE DAMOS PASSWORD,DAMOS PERMISO DE USO Y DAMOS PERMISOS SOBRE LA BASE DE DATOS.
--
CREATE USER IF NOT EXISTS `PADELDB`@`localhost` IDENTIFIED BY 'ABP16';
GRANT USAGE ON *.* TO `PADELDB`@`localhost` REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `PADELDB`.* TO `PADELDB`@`localhost` WITH GRANT OPTION;

CREATE TABLE IF NOT EXISTS `USUARIO` (
  LOGIN varchar(15) NOT NULL,
  PASSWORD varchar(128) NOT NULL,
  NOMBRE varchar(30) NOT NULL,
  APELLIDOS varchar(50) NOT NULL,
  DNI varchar(9) NOT NULL UNIQUE,
  EMAIL varchar(60) NOT NULL UNIQUE,
  TELEFONO varchar(11) NOT NULL,
  AVATAR varchar(50) NOT NULL,
  ACEPTADO enum('SI','NO') DEFAULT 'NO',
  ROL enum('ADMIN','DEPORTISTA','ENTRENADOR') NOT NULL,
  BORRADO enum('SI','NO') DEFAULT 'NO',
  SEXO enum('MASC','FEM','OTRO'),


PRIMARY KEY (LOGIN)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;




CREATE TABLE IF NOT EXISTS `PISTA` (
  ID_PISTA int(255) NOT NULL UNIQUE,
  RESERVADA enum('SI','NO') DEFAULT 'NO',


PRIMARY KEY (ID_PISTA)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `RESERVA_PISTA`(
  ID_PISTA int(255) NOT NULL UNIQUE,
  ID_RESPONSABLE int(255),
  RESERVADA enum('SI','NO'),
  ID_RESERVA int(255) AUTO_INCREMENT NOT NULL,
  
  PRIMARY KEY(ID_RESERVA),
  FOREIGN KEY(ID_PISTA) REFERENCES PISTA (ID_PISTA)
  
)ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `ENTRENADOR`(
  ID_ENTRENADOR int(255) UNIQUE,
  LOGIN int(255) NOT NULL,

  

PRIMARY KEY(ID_ENTRENADOR),
FOREIGN KEY(LOGIN) REFERENCES USUARIO (LOGIN)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `CALENDARIO`(
  FECHA_COMPLETA varchar(10),
  DIA int(2),
  MES int(2),
  AÑO int(4),
  DIA_SEMANA enum('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO'),
    
  PRIMARY KEY(FECHA_COMPLETA)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `HORA_CALENDARIO`(
  HORA int(2),
  MINUTE int(2),
  SECOND int(2),
  HORA_COMPLETA varchar(8),

  PRIMARY KEY(HORA_COMPLETA)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;


